---
title: "Bayesian Data Analysis course - Project work"
author: "Giorgio Corani - SUPSI"
date: 'Bayesian Data analysis and Probabilistic Programming'
output:
  beamer_presentation:
    latex_engine: xelatex
    fig_width: 6
    fig_height: 3
    highlight: tango
    theme: metropolis
    includes:
      in_header: header.tex
fontsize: 13pt

---

## Project work details

The project requires choosing a data set and analyzing it using the methodologies learned during  the course.

# Groups  
* The project is done by a group of two persons. 
* In case of strong disagreement with your mate, you can ask to perform the project on your own (the amount of the work is however the same of the 2-persons project).

# Evaluation

* The final grade of the course is:
  * 75%: evaluation of the project 
  * 25% evaluation of the assignment


* **fare presentazione o solo orale?? **

* Suspected plagiarism will be investigated and  can lead to a null grade.




# Project content

The project  presents the problem and data
analysis results;  a minimal listing of code and figures
is not enough. 

To keep the report readable, some
diagnostic outputs and code can be put in the appendix. 
If you are uncertain you can ask TAs about such choices.

The report should include

1. Description of the data and how you collected them.

  1. Description of at least two models, for example:
      - non hierarchical and hierarchical,
      - linear and non linear,
      - classification and regression.
      
  1. Justification of the  choices of the prior.
  
  1. The most important parts of the model implementation in  pymc3.
  
At least for one model, discuss:  
  * Convergence diagnostics ($\widehat{R}$, ESS, divergences)     * Posterior predictive checks and what was done to improve the model.
  * Model comparison (e.g. with WAIC).
  1. Predictive performance assessment if applicable (e.g. classification
    accuracy) and evaluation of practical usefulness of the accuracy.
  * Sensitivity analysis with respect to prior choices (i.e. checking whether the result changes a lot if prior is changed)

# Project presentation

  - The duration of the presentation should be 10 minutes (groups of 1-2 students) or 15 minutes (groups of 3 students).
  - At the end of the presentation there will be an extra 5-10 minutes of
    questions by anyone in the audience or two members of the course staff who are presenr. The questions from lecturer/TAs can be considered as an oral exam questions, and if answers to these questions reveal weak knowledge of the methods and workflow steps which should be part of the project, that can reduce the grade.
    
# Data sets

* It's best to use a dataset for which there is no ready made analysis in internet, and possibly collected by you.

* It is ok to re-use a data set you already collected for another course during the Bachelor.
but if you choose a dataset used already in some online case study, provide the link to previous studies and report how your analysis differs from those (for example if someone has made non-Bayesian analysis and you do the full Bayesian analysis).



# Examples (da statistica applicata)
